data:
    dataset_type: "bathroom"
    encoding_type: "autoregressive_wocm"
    dataset_directory: "data/preprocessed_4ch"
    train_split_file: "data/train_scenes.txt"
    val_split_file: "data/val_scenes.txt"
    test_split_file: "data/test_scenes.txt"
    #augmentations: ["rotations"]
    #augmentations: ["jitter"]
    augmentations: []
    filter_fn: "bathroom"
    train_stats: "dataset_stats.txt"
    room_layout_size: "64,64"
network:
    type: "autoregressive_transformer"
    n_layers: 4
    n_heads: 8
    query_dimensions: 64
    value_dimensions: 64
    feed_forward_dimensions: 1024
    hidden2output_layer: "autoregressive_mlc"
    hidden_dims: 512
    with_extra_fc: false
    bbox_output: "autoregressive_mlc"
    n_mixtures: 10
    use_room_mask_as_features: true
feature_extractor:
    name: "resnet18"
    feature_size: 64
    freeze_bn: true
    #input_channels: 1
    input_channels: 4
training:
    splits: ["train", "val"]
    save_frequency: 1
    optimizer: Adam
    lr: 0.0001
    weight_decay: 0.0

    # Instant
    #epochs: 2
    #steps_per_epoch: 10
    #batch_size: 4

    # 10min CPU, Test
    #epochs: 50
    #steps_per_epoch: 100
    #batch_size: 4

    # 50 min CPU, 30%
    #epochs: 50
    #steps_per_epoch: 440
    #batch_size: 4

    # 2.5 hour CPU, 50%
    #epochs: 150
    #steps_per_epoch: 440
    #batch_size: 4

    # 5 hour CPU, 40%
    # Can overfit
    epochs: 300
    steps_per_epoch: 440
    batch_size: 4

    # 30min GPU, 80%, paper batch used 128
    #epochs: 150
    #steps_per_epoch: 440
    #batch_size: 16

    # 24 hours GPU, 100%
    #epochs: 150
    #steps_per_epoch: 440
    #batch_size: 128

validation:
    splits: ["test"]
    frequency: 1
    batch_size: 4
logger:
    type: "tensorboard"
    project: "bathroom_layout_test"
